# 示例副本模板配置文件

# 基本信息
name: "example"                # 模板名称（必须与文件夹名称相同）
displayName: "&6示例副本"       # 显示名称（支持颜色代码）
worldDisplay: "&6深渊龙穴"      # 世界显示名称（用于%sd_display%占位符）
description: "这是一个示例副本，用于展示SagaDungeons的功能。" # 描述
defaultTimeout: 1800           # 默认超时时间（秒）
maxPlayers: 5                  # 最大玩家数

# 游戏模式设置
forceGameMode: true            # 是否强制游戏模式（默认：true）
gameMode: "ADVENTURE"          # 强制的游戏模式（SURVIVAL、CREATIVE、ADVENTURE、SPECTATOR）

# 禁止指令列表
# 在副本中禁止使用的指令，防止玩家通过其他插件的传送功能绕过副本机制
blockCMDList:
  - "tp"
  - "tpa"
  - "tpaccept"
  - "tpahere"
  - "home"
  - "sethome"
  - "spawn"
  - "warp"
  - "back"
  - "mv"
  - "mvtp"
  - "world"

# 世界路径配置
# 指定副本世界模板的路径，相对于插件目录
# 例如: "templates/example/world" 表示使用 plugins/SagaDungeons/templates/example/world 目录作为世界模板
# 如果不指定，默认使用 templates/[模板名称] 目录
worldPath: "templates/example/world"

# 创建条件
creationConditions:
  # 条件启用状态
  # 设置为true表示启用该条件，false表示禁用
  levelEnabled: true    # 是否启用等级条件

  # 等级条件
  level: 10

# 死亡限制
deathLimit: 0

# 复活道具
#reviveItem:
  # 方式一：使用材质和名称
#  material: GOLDEN_APPLE
#  name: "复活苹果"

  # 方式二：使用序列化物品（二选一，优先使用序列化物品）
  # serialized-item: 'rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGphdmEvdXRpbC9NYXA7eHBzcgE1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAR0AAI9PXQABHR5cGV0AAxkaXNwbGF5TmFtZXQABGxvcmV1cQB+AAYAAAAEdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAQVE9URU1fT0ZfVU5EWUlOR3QAEsKnNuWIhuacrOWkjeaWsOWbvnQAEMKnN+mHkeWTiOmHkeWTiOmHkeWTiA=='

#单一通关条件示例 - 到达区域
#completion:
#  reachArea:
#    x: 5
#    y: 5
#    z: 5
#    range: 10

#当前使用的单通关条件
completion:
  killSpecific:
    mobName: "SkeletonKing"
    count: 9

# MythicMobs刷怪点
mythicMobsSpawners:
  spawner1:
    mobType: "SkeletonKing"
    location: "world,100,64,100"
    cooldown: 30
    amount: 1

  spawner2:
    mobType: "ZombieHorde"
    location: "world,110,64,110"
    cooldown: 60
    amount: 5