# 示例副本模板配置文件

# 基本信息
name: "example"                # 模板名称（必须与文件夹名称相同）
displayName: "&6示例副本"       # 显示名称（支持颜色代码）
worldDisplay: "&6深渊龙穴"      # 世界显示名称（用于%sd_display%占位符）
description: "这是一个示例副本，用于展示SagaDungeons的功能。" # 描述
defaultTimeout: 1800           # 默认超时时间（秒）
maxPlayers: 5                  # 最大玩家数

# 游戏模式设置
forceGameMode: true            # 是否强制游戏模式（默认：true）
gameMode: "ADVENTURE"          # 强制的游戏模式（SURVIVAL、CREATIVE、ADVENTURE、SPECTATOR）

# 禁止指令列表
# 在副本中禁止使用的指令，防止玩家通过其他插件的传送功能绕过副本机制
blockCMDList:
  - "tp"
  - "tpa"
  - "tpaccept"
  - "tpahere"
  - "home"
  - "sethome"
  - "spawn"
  - "warp"
  - "back"
  - "mv"
  - "mvtp"
  - "world"

# 世界路径配置
# 指定副本世界模板的路径，相对于插件目录
# 例如: "templates/example/world" 表示使用 plugins/SagaDungeons/templates/example/world 目录作为世界模板
# 如果不指定，默认使用 templates/[模板名称] 目录
worldPath: "templates/example/world"

# 创建条件
creationConditions:
  # 条件启用状态
  # 设置为true表示启用该条件，false表示禁用
  moneyEnabled: true    # 是否启用金币条件
  pointsEnabled: true   # 是否启用点券条件
  levelEnabled: true    # 是否启用等级条件
  itemsEnabled: true    # 是否启用物品条件

  # 金币条件（需要Vault）
  money: 100

  # 点券条件（需要PlayerPoints）
  points: 10

  # 等级条件
  level: 10

  # 物品条件
  items:
    item1:
      material: DIAMOND
      amount: 1
      name: "特殊钻石"
      lore:
        - "这是一个特殊的钻石"
        - "用于创建副本"

    # 序列化物品示例
    # serialized-item: 'rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAR0AAI9PXQABHR5cGV0AAxkaXNwbGF5TmFtZXQABGxvcmV1cQB+AAYAAAAEdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAER09MRHQAEMKnZcKnbOmHkeWTiOmHkeWTiHQAEMKnN+mHkeWTiOmHkeWTiOmHkeWTiA=='

# 死亡限制
deathLimit: 0

# 复活道具
#reviveItem:
  # 方式一：使用材质和名称
#  material: GOLDEN_APPLE
#  name: "复活苹果"

  # 方式二：使用序列化物品（二选一，优先使用序列化物品）
  # serialized-item: 'rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAR0AAI9PXQABHR5cGV0AAxkaXNwbGF5TmFtZXQABGxvcmV1cQB+AAYAAAAEdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAQVE9URU1fT0ZfVU5EWUlOR3QAEsKnNuWIhuacrOWkjeaWsOWbvnQAEMKnN+mHkeWTiOmHkeWTiOmHkeWTiA=='


#组合OR通关条件
#completion:
#  composite:
#    type: OR
#    priority: 1
#    conditions:
#      killSpecific:
#        mobName: "Boss"
#      killCount:
#        count: 20

#组合AND通关条件
#completion:
#  composite:
#    type: AND
#    priority: 1
#    conditions:
#      killCount:
#        count: 10
#      reachArea:
#        location: "world,100,64,100"
#        radius: 3.0

#多级通关条件
#completion:
#  composite:
#    type: AND
#    priority: 1
#    conditions:
#      condition1:
#        composite:
#          type: OR
#          priority: 2
#          conditions:
#            killSpecific:
#              mobName: "Boss"
#            killCount:
#              count: 20
#      condition2:
#        reachArea:
#          location: "world,100,64,100"

#单一通关条件
completion:
  killSpecific:
    mobName: "SkeletonKing"

#          radius: 3.0
# 奖励
rewards:
  # 金币奖励（需要Vault）
  money: 1000

  # 点券奖励（需要PlayerPoints）
  points: 100

  # 经验奖励
  experience: 500

  # 物品奖励
  items:
    # 方式一：使用材质和名称
    item1:
      material: DIAMOND_SWORD
      amount: 1
      name: "传说之剑"
      lore:
        - "这是一把传说中的剑"
        - "只有完成副本的勇士才能获得"

    item2:
      material: GOLDEN_APPLE
      amount: 5
      name: "奖励金苹果"
      lore:
        - "副本奖励"

    # 方式二：使用序列化物品
    # serialized-item:
    #   serialized-item: 'rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAR0AAI9PXQABHR5cGV0AAxkaXNwbGF5TmFtZXQABGxvcmV1cQB+AAYAAAAEdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAHRElBTU9ORHQAEMKnYuWIhuacrOmTtuefs3QAEMKnN+mHkeWTiOmHkeWTiOmHkeWTiA=='
    #   amount: 10

  # 命令奖励
  commands:
    command1:
      command: "give %player% minecraft:diamond 10"
      description: "获得10个钻石"

    command2:
      command: "broadcast %player% 完成了示例副本！"
      description: "全服公告"

# MythicMobs刷怪点
mythicMobsSpawners:
  spawner1:
    mobType: "SkeletonKing"
    location: "world,100,64,100"
    cooldown: 30
    amount: 1

  spawner2:
    mobType: "ZombieHorde"
    location: "world,110,64,110"
    cooldown: 60
    amount: 5

# 时间奖励配置 - 根据完成时间给予不同奖励
# 时间格式支持：3600（秒）、"1h"（小时）、"90m"（分钟）、"30s"（秒）
# 注意：时间越短奖励越好，系统会自动选择符合条件的最佳奖励
timeRewards:
  # 1小时内完成 - 最高奖励
  "1h":
    commands:
      - "give %player% diamond 5"
      - "eco give %player% 1000"
      - "say %player% 在1小时内完成了副本，获得钻石奖励！"

  # 1.5小时内完成 - 中等奖励
  "90m":
    commands:
      - "give %player% gold_ingot 10"
      - "eco give %player% 500"
      - "say %player% 在1.5小时内完成了副本，获得金锭奖励！"

  # 2小时内完成 - 基础奖励
  "2h":
    commands:
      - "give %player% iron_ingot 20"
      - "eco give %player% 200"
      - "say %player% 在2小时内完成了副本，获得铁锭奖励！"
